[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers =
    courses: для тестов, связанных с курсами
    regression: для регрессионных тестов
    ui: Маркировка для UI тестов
    smoke: Маркировка для smoke тестов
    slow: Маркировка для slow тестов
    critical: Маркировка для critical тестов
    dashboard: Маркировка для тестов рабочей панели
    registration: Маркировка для registration тестов
    authorization: Маркировка для Auth тестов

